config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  get 'group_users/create'
  get 'group_users/destroy'
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'searches#search'
  devise_for :users
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :following, :followers
    end
    resources :user_chats, only: [:index, :create]
  end
  resources :books,only: [:show, :index, :edit, :create, :update, :destroy]do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
    get :post_count, on: :collection
    get :sort_new_arrival, on: :collection
    get :sort_evaluation, on: :collection
    get :category_search, on: :collection
  end
  resources :relationships, only: [:create, :destroy]
  resources :groups, only: [:show, :index, :new, :create, :edit, :update] do
    get :sent_mail_new, on: :collection
    get :sent_mail_create, on: :collection
  end
  resources :group_users, only: [:create, :destroy]
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  attachment :image

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def show
    @group = Group.find(params[:id])
    @owner = User.find(@group.owner_id)
    @members = @group.users
  end

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @groups = Group.all
    if @group.save
      user = User.find(@group.owner_id)
      user.join(@group)
      redirect_to groups_path, notice: "You have created group successfully."
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
    redirect_to groups_path unless current_user.owned?(@group)
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path, notice: 'You habe updated group successfully.'
    else
      render 'edit'
    end
  end

  def sent_mail_new
    @group = Group.find(params[:group_id])
  end

  def sent_mail_create
    @title = params[:title]
    @content = params[:content]
    @group = Group.find(params[:group_id])
    users = @group.users
    users.each do |user|
      @user = user
      UserMailer.group_notice(@user, @group, @title, @content).deliver_now
    end

  end

  private

    def group_params
      params.require(:group).permit(:name, :introduction, :image)
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= attachment_image_tag(group, :image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= link_to group.name, group_path(group) %></td>
        <td><%= group.introduction %></td>
        <td>メンバー数：<%= group.users.count %></td>
        <td>
          <% if current_user.owned?(group) %>
            <%= link_to 'Edit', edit_group_path(group), class: 'btn btn-success' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/_member_list.html.erb
<% members.each do |member| %>
  <p><%= member.name %></p>
<% end %>

app/views/groups/_member_list_btn.html.erb
<% if current_user.owned?(group) %>
  <%= link_to 'Edit', edit_group_path(group), class:'btn btn-success' %>
<% else %>
  <% if current_user.joined?(group) %>
    <%= link_to 'Leave this group', group_user_path(group.id), method: :delete, remote: true, class:'btn btn-danger' %>
  <% else %>
    <%= link_to 'Join this group', group_users_path(group_id: group.id), method: :post, remote: true,  class:'btn btn-success' %>
  <% end %>
<% end %>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Editing Group</h2>
    <%= form_with model:@group, local:true do |f| %>
      <%= render 'layouts/errors', obj: @group %>
      <div class="form-group">
        <%= f.label :name, 'グループ名' %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction, '紹介文' %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :image, class: "form-control-file image" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <%= render 'index',groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Create Group</h2>
    <%= form_with model:@group, local:true do |f| %>
      <%= render 'layouts/errors', obj: @group %>
      <div class="form-group">
        <%= f.label :name, 'グループ名' %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction, '紹介文' %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :image, class: "form-control-file image" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/sent_mail_create.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>送信が完了しました。</h2>
    <p>内容は以下の通りです。</p>
    <p>
      [タイトル]<br>
      <%= @title %>
    </p>
    <p>
      [本文]<br>
      <%= @content %>
    </p>
  </div>
</div>

app/views/groups/sent_mail_new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Event Mail</h2>
    <%= form_with(url: sent_mail_create_groups_path, method: :get, local: true) do |f| %>
      <%= f.hidden_field :group_id ,:value => @group.id %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: "form-control introduction" %>
      </div>
      <div class="form-group d-flex">
        <%= f.submit '送信', class: 'btn btn-success ml-auto' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @owner %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table '>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= attachment_image_tag(@group, :image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td id='member_list'>
              <%= render 'member_list', members: @members %>
            </td>
            <td id='member_list_btn'>
              <%= render 'member_list_btn', group: @group %>
            </td>
            <td>
              <% if current_user.owned?(@group) %>
                <%= link_to 'Notice an Event', sent_mail_new_groups_path(group_id: @group.id), class: 'btn btn-info' %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>