config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  get 'group_users/create'
  get 'group_users/destroy'
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'searches#search'
  devise_for :users
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :following, :followers
    end
    resources :user_chats, only: [:index, :create]
  end
  resources :books,only: [:show, :index, :edit, :create, :update, :destroy]do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
    get :post_count, on: :collection
    get :sort_new_arrival, on: :collection
    get :sort_evaluation, on: :collection
    get :category_search, on: :collection
  end
  resources :relationships, only: [:create, :destroy]
  resources :groups, only: [:show, :index, :new, :create, :edit, :update] do
    get :sent_mail_new, on: :collection
    get :sent_mail_create, on: :collection
  end
  resources :group_users, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :passive_relationships,  source: :follower
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :active_user_chats, class_name: 'UserChat', foreign_key: 'send_user_id', dependent: :destroy
  has_many :send_users, through: :active_user_chats, source: :send_user
  has_many :passive_user_chats, class_name: 'UserChat', foreign_key: 'receive_user_id', dependent: :destroy
  has_many :receive_users, through: :passive_user_chats, source: :receive_user

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50 }

  # 追加メソッド

  #ユーザをフォローする
  def follow(other_user)
    following << other_user
  end

  #ユーザをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  #現在のユーザがフォローしていたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  #relationShipIdを返す
  def follow_id(other_user)
    active_relationships.find_by(folowed_id: other_user.id).id
  end

  #nameで検索したレコードを返す
  def self.search(search_method,word)
    if search_method == '完全一致'
      @contents = User.where("name=?","#{word}")
    elsif search_method == '前方一致'
      @contents = User.where("name LIKE?","#{word}%")
    elsif search_method == '後方一致'
      @contents = User.where("name LIKE?","%#{word}")
    else
      @contents = User.where("name LIKE?","%#{word}%")
    end
  end

  #グループのオーナーであればtrueを返す
  def owned?(group)
    self.id == group.owner_id
  end

  #グループに所属する
  def join(group)
    groups << group
  end

  #グループから抜ける
  def leave_group(group)
    group_users.find_by(group_id: group.id).destroy
  end

  #ユーザがグループに所属していたらtrueを返す
  def joined?(group)
    groups.include?(group)
  end

  #ユーザと他のユーザとのチャット履歴を返す
  def chat_index(other_user)
    chat_index = UserChat.where(send_user_id: self.id, receive_user_id: other_user.id).or(UserChat.where(send_user_id: other_user.id, receive_user_id: self.id))
    chat_index.sort { |a,b| a.id <=> b.id}
  end

  #ユーザのn日前からm日前の期間の投稿数を返す
  def post_count(n,m)
    range = Date.current.ago(n.days).beginning_of_day..Date.current.ago(m.days).end_of_day
  	Book.where(user_id: self.id, created_at: range).length
  end

  #ユーザの指定したn日の投稿数を返す
  def post_count_date(date)
    range = date.beginning_of_day..date.end_of_day
    Book.where(user_id: self.id, created_at: range).length
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books.sort { |a,b| b.a_week_favorited_count <=> a.a_week_favorited_count }
    @book = Book.new

    # 投稿数用
    @post_count = 0

    # @post_count = []
    # (0..6).each do |n|
    #   @post_count.push(@user.post_count(n,n))
    # end

    # if @post_count[1] == 0
    #   @day_before_ratio = '-'
    # else
    #   @day_before_ratio = @post_count[0]*100 / @post_count[1]
    # end
    # @post_count_this_week = @user.post_count(6,0)
    # @post_count_last_week = @user.post_count(13,7)
    # if @post_count_last_week == 0
    #   @week_before_ratio = '-'
    # else
    #   @week_before_ratio = @post_count_this_week*100 / @post_count_last_week
    # end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless current_user == @user
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def following
    @title = 'Follow'
    @users = User.find(params[:id]).following
    render 'follow'
  end

  def followers
    @title = 'Follower'
    @users = User.find(params[:id]).followers
    render 'follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def ensure_correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% unless user == current_user %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete %>
            <% else %>
              <%= link_to 'フォローする', relationships_path(followed_id: user.id) , method: :post  %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}", 'data-turbolinks': false %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <a href='<%= following_user_path(user) %>'>
        <%= user.following.count %>
      </a>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <a href='<%= followers_user_path(user) %>'>
        <%= user.followers.count %>
      </a>
    </th>
  </tr>
</table>

<div class='row'>
  <!-- ログインユーザなら編集ボタン、それ以外ならフォローボタンを表示 -->
  <% if user == current_user %>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% else %>
    <% if current_user.following?(user) %>
      <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id),
        html: { method: :delete}, local: true) do |f| %>
        <%= f.submit 'フォロー外す', class: 'btn btn-info' %>
      <% end %>
      <% if user.following?(current_user) %>
        <%= link_to 'chatを始める', user_user_chats_path(user_id: user.id), class:'m-auto' %>
      <% end %>
    <% else %>
      <%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
        <div><%= hidden_field_tag :followed_id, user.id %></div>
        <%= f.submit 'フォローする', class: 'btn btn-success' %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/_post.html.erb
<h2>7日間分の投稿数</h2>
      <table class='table table-bordered'>
        <thead>
          <tr>
            <td>6日前</td>
            <td>5日前</td>
            <td>4日前</td>
            <td>3日前</td>
            <td>2日前</td>
            <td>1日前</td>
            <td>今日</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= post_count[6] %></td>
            <td><%= post_count[5] %></td>
            <td><%= post_count[4] %></td>
            <td><%= post_count[3] %></td>
            <td><%= post_count[2] %></td>
            <td><%= post_count[1] %></td>
            <td><%= post_count[0] %></td>
          </tr>
        </tbody>
      </table>

app/views/users/_post_graph.html.erb
<canvas id='post_line_chart'></canvas>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js'></script>

<script>
// $(document).on('turbolinks:load',function(){
  const ctx = document.getElementById('post_line_chart')
  const post_line_chart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日' ],
      datasets: [
        {
          label: '投稿した本の数',
          data: [
            <%= post_count[6]%>,
            <%= post_count[5]%>,
            <%= post_count[4]%>,
            <%= post_count[3]%>,
            <%= post_count[2]%>,
            <%= post_count[1]%>,
            <%= post_count[0]%>,
            ],
          borderColor: 'rgba(0,0,255,1)',
          backgroundColor: 'rgba(0,0,0,0)'
        }
      ],
    },
    options: {
      title: {
        display: true,
        text: '7日間の投稿数の比較'
      },
      scales: {
        yAxes: [{
          ticks: {
            suggestedMax: 10,
            suggestedMin: 0,
            stepSize: 1
          }
        }]
      },
    }
  });
// });
</script>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/follow.html.erb
<h1><%= @title %> Users</h1>

<% if @users.length == 0 %>
  <p>ユーザーはいません</p>
<% else %>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan='3'></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: 'no-image-icon.jpg') %>
            <% end %>
          </td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.following.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <td>
            <%= link_to 'Show', user_path(user) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to 'グループを作成する', new_group_path %>
      <span> | </span>
      <%= link_to 'グループ一覧', groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <div id='user_show_books_index'>
        <%= render 'books/index',books: @books %>
      </div>
      <!-- 投稿テーブル -->
      <!--< %= render 'post', post_count: @post_count %>-->
      <!-- 投稿グラフ -->
      <!--< %= render 'post_graph', post_count: @post_count %>-->
      <%= form_with url: post_count_books_path, method: :get, remote: true do |f| %>
        <%= f.hidden_field :user_id, :value => @user.id %>
        <%= f.date_field :date %>
        <%= f.submit '検索', class:'btn btn-primary' %>
      <% end %>
      <h4>検索結果</h4>
      <table class='table table-bordered'>
        <thead>
          <tr>
            <td>投稿数</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td id='post_count'><%= @post_count %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>