config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  get 'group_users/create'
  get 'group_users/destroy'
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'searches#search'
  devise_for :users
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :following, :followers
    end
    resources :user_chats, only: [:index, :create]
  end
  resources :books,only: [:show, :index, :edit, :create, :update, :destroy]do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
    get :post_count, on: :collection
    get :sort_new_arrival, on: :collection
    get :sort_evaluation, on: :collection
    get :category_search, on: :collection
  end
  resources :relationships, only: [:create, :destroy]
  resources :groups, only: [:show, :index, :new, :create, :edit, :update] do
    get :sent_mail_new, on: :collection
    get :sent_mail_create, on: :collection
  end
  resources :group_users, only: [:create, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user
	has_many :book_comments, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	#追加メソッド

	#いいねしているかどうかを調べる
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	#1週間以内にいいねされた数を返す
	def a_week_favorited_count
		self.favorites.where(:updated_at => 1.week.ago..Time.now).length
	end

	#titleで検索したレコードを返す
	def self.search(search_method,word)
    if search_method == '完全一致'
      @contents = Book.where("title=?","#{word}")
    elsif search_method == '前方一致'
      @contents = Book.where("title LIKE?","#{word}%")
    elsif search_method == '後方一致'
      @contents = Book.where("title LIKE?","%#{word}")
    else
      @contents = Book.where("title LIKE?","%#{word}%")
    end
  end

  #閲覧数を一つ増やす
  def pvcount_up
  	pvcount = self.pvcount
  	pvcount += 1
  	self.update_attribute(:pvcount, pvcount)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @book.pvcount_up
    @comment = BookComment.new
  end

  def index
    @books = Book.all #.sort { |a,b| b.a_week_favorited_count <=> a.a_week_favorited_count } 課題8dのためにいいね順をストップ
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.pvcount = 0
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless @book.user == current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def post_count
    user = User.find(params[:user_id])
    date = params[:date].to_date
    @post_count = user.post_count_date(date)
  end

  def sort_new_arrival
    if category = params[:category]
      @books = Book.where(category: category).sort { |a,b| a.id <=> b.id }
    else
      @books = Book.all.sort { |a,b| a.id <=> b.id }
    end
  end

  def sort_evaluation
    if category = params[:category]
      @books = Book.where(category: category).sort { |a,b| b.rate.to_i <=> a.rate.to_i }
    else
      @books = Book.all.sort { |a,b| b.rate.to_i <=> a.rate.to_i }
    end
  end

  def category_search
    @category = params[:category]
    @books = Book.where(category: @category)
    @book = Book.new
  end

  private

    def book_params
      params.require(:book).permit(:title, :body, :rate, :category)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class='form-group'>
    <%= f.label :category %>
    <%= f.text_field :category, class: 'form-control' %>
  </div>
  <div class='form-group' id='star'>
    <%= f.label :rate %>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

<!-- 5段階評価javascript -->
<script>
  $('#star').raty({
    starOff: '<%= asset_path('star-off.png') %>',
    starOn: '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'book[rate]',
    half: true
  });
</script>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= link_to book.category, category_search_books_path(category: book.category) %></td>
        <td>
          <div id="favorite_btn_<%= book.id %>">
            <%= render 'favorites/favorite_btn', book: book %>
          </div>
        </td>
        <td>コメント数：<%= book.book_comments.count %></td>
        <td class='book_rate' data-score='<%= book.rate %>'></td>
        <!--<td>閲覧数：<%= book.pvcount %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<!-- 5段階評価のJS -->
<script>
  $('.book_rate').raty({
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/books/category_search.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <!-- カテゴリー検索か通常の一覧表示かどうかで分ける-->
      <% if @category %>
        <%= link_to '新しい順', sort_new_arrival_books_path(category: @category), remote: true %>
        <span> | </span>
        <%= link_to '評価の高い順', sort_evaluation_books_path(category: @category), remote: true %>
      <% else %>
        <%= link_to '新しい順', sort_new_arrival_books_path, remote: true %>
        <span> | </span>
        <%= link_to '評価の高い順', sort_evaluation_books_path, remote: true %>
      <% end %>
      <div id='books_index_books_index'>
        <%= render 'index', books: @books%>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= form_with model:@book,local:true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
        <div class='form-group'>
          <%= f.label :category %>
          <%= f.text_field :category, class: 'form-control' %>
        </div>
        <div class='book_rate form-group' data-score='<%= @book.rate %>'></div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

<!-- 5段階評価のJS -->
<script>
  $('.book_rate').raty({
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to '新しい順', sort_new_arrival_books_path, remote: true %>
      <span> | </span>
      <%= link_to '評価の高い順', sort_evaluation_books_path, remote: true %>
      <div id='books_index_books_index'>
        <%= render 'index', books: @books%>
      </div>
    </div>
  </div>
</div>

app/views/books/post_count.js.erb
$("#post_count").html("<%= @post_count %>");

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @newbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td>
  		      <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag(@book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td><%= @book.category %></td>
          <td>
            <div id="favorite_btn_<%= @book.id %>">
              <%= render 'favorites/favorite_btn', book: @book %>
            </div>
          </td>
          <td id='book_comments_count'>コメント数：<%= @book.book_comments.count %></td>
          <td class='book_rate' data-score='<%= @book.rate %>'></td>
          <!--<td>閲覧数：<%= @book.pvcount %></td>-->
          <% if current_user == @book.user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <!-- コメント入力欄 -->
      <div id='book_comments_index'>
        <%= render 'book_comments/comments_index', book: @book %>
      </div>

      <div id='book_comment_input'>
        <%= form_with(model:[@book,@comment], remote: true)do |f| %>
          <%= f.text_area :comment, rows:'5' %>
          <%= f.submit '送信' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- 5段階評価のJS -->
<script>
  $('.book_rate').raty({
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/books/sort_evaluation.js.erb
$('#books_index_books_index').html("<%= j(render partial: 'books/index', locals: {books: @books}) %>");

app/views/books/sort_new_arrival.js.erb
$('#books_index_books_index').html("<%= j(render partial: 'books/index', locals: {books: @books}) %>");